version: '3.1'

services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.production
    volumes:
      - '.:/app'
    ports:
      # - 3000:3000
      - 3000:80
    # environment:
    #   CHOKIDAR_USEPOLLING: 'true'