export const RECURRENCE_FIELDS = [
  "recur_freq",
  "recur_interval",
  // "recur_wkst",
  "recur_bymonth",
  // "recur_byweekno",
  // "recur_byyearday",
  "recur_bymonthday",
  // "recur_byday",
  // "recur_byhour",
  // "recur_byminute",
  // "recur_bysecond",
  // "recur_bysetpos",
  "recur_until",
  "recur_count",
] as const;