export const TRANSACTION_TYPE_INCOME = 'income';
export const TRANSACTION_TYPE_EXPENSE = 'expense';
export const TRANSACTION_TYPE_TRANSFER = 'transfer';
export const TRANSACTION_TYPES = [
  TRANSACTION_TYPE_INCOME,
  TRANSACTION_TYPE_EXPENSE,
  TRANSACTION_TYPE_TRANSFER,
];
