const TRANSACTION_TYPE_INCOME = 'income';
const TRANSACTION_TYPE_EXPENSE = 'expense';
const TRANSACTION_TYPE_TRANSFER = 'transfer';

module.exports = {
  TRANSACTION_TYPE_INCOME,
  TRANSACTION_TYPE_EXPENSE,
  TRANSACTION_TYPE_TRANSFER,

};
